package com.libra.community.model;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAG.ID
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAG.ACCOUNT_ID
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAG.TAG
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAG.TAG_TYPE
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    private Integer tagType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAG.GMT_CREATE
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TAG.GMT_MODIFIED
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAG.ID
     *
     * @return the value of TAG.ID
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAG.ID
     *
     * @param id the value for TAG.ID
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAG.ACCOUNT_ID
     *
     * @return the value of TAG.ACCOUNT_ID
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAG.ACCOUNT_ID
     *
     * @param accountId the value for TAG.ACCOUNT_ID
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAG.TAG
     *
     * @return the value of TAG.TAG
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAG.TAG
     *
     * @param tag the value for TAG.TAG
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAG.TAG_TYPE
     *
     * @return the value of TAG.TAG_TYPE
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    public Integer getTagType() {
        return tagType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAG.TAG_TYPE
     *
     * @param tagType the value for TAG.TAG_TYPE
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    public void setTagType(Integer tagType) {
        this.tagType = tagType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAG.GMT_CREATE
     *
     * @return the value of TAG.GMT_CREATE
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAG.GMT_CREATE
     *
     * @param gmtCreate the value for TAG.GMT_CREATE
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TAG.GMT_MODIFIED
     *
     * @return the value of TAG.GMT_MODIFIED
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TAG.GMT_MODIFIED
     *
     * @param gmtModified the value for TAG.GMT_MODIFIED
     *
     * @mbg.generated Fri Mar 06 17:30:07 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}